env:
  node: true
  es2021: true
  jest: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@stylistic'
extends:
  - airbnb-base
rules:
  import/extensions: off
  semi: [error, never]
  'eol-last': [error, always]
  'arrow-parens': [error, as-needed]
  'quote-props': [error, consistent-as-needed]
  'comma-dangle': [error, never]
  'object-curly-spacing': [error, always]
  'array-bracket-spacing': [error, never]
  'space-before-function-paren': [error, never]
  'operator-linebreak': [error, after]
  'no-console': off           
  'max-len': [error, {
    code: 120,
    ignoreComments: true,
    ignoreTrailingComments: true,
    ignoreUrls: true
  }]